### ISSUE TITLE
Different instructions if .zip file is downloaded

### ISSUE THREAD

**Issue by dixonge** [cleverdevil/ditchbook#2]
setup.py is not in the /ditchbook folder - you have to ```cd ..``` first before running that step

**Comment by cleverdevil** [comment]
Pull requests welcome to improve the user experience!

**Comment by dixonge** [comment]
well I would normally do that, but since your instructions were for git clone, and I was starting with a download and not using git, I wasn't sure how to handle it. If you just move that setup.py file down one level then the existing instructions would be fine?

**Comment by cleverdevil** [comment]
Nope, you can't move the files around.

**Comment by dixonge** [comment]
so maybe change that one line to ```python ../setup.py develop``` ?

**Comment by cleverdevil** [comment]
It really is going to depend on how the user uncompresses the zip file. Some tools put the contents into a subdirectory, others put the contents in the current directory. I think its likely best to keep the instructions explicit with using git to clone the contents.

What the user needs to do is to change into the directory containing setup.py and run `python setup.py develop`.

**Comment by dixonge** [comment]
I was able to use git clone by changing the syntax slightly.

```git clone https://github.com/cleverdevil/ditchbook.git```

This bypasses the permission error if you don't have a public key set up on your local machine.
