### ISSUE TITLE
bin/ingest export errors

### ISSUE THREAD

**Issue by dixonge** [cleverdevil/ditchbook#3]
First I got this error:

```Traceback (most recent call last):
  File "bin/ingest", line 3, in <module>
    from ditchbook.ingest import process_album, process_post
  File "/home/donblanco/ditchbook-master/ditchbook/ingest.py", line 1, in <module>
    from ditchbook import micropub
  File "/home/donblanco/ditchbook-master/ditchbook/micropub.py", line 4, in <module>
    import conf
ModuleNotFoundError: No module named 'conf'```

So even though it isn't called for until the next step, I went ahead and copied and configured conf.py - then I ran ingest again and got this error:

```Traceback (most recent call last):
  File "bin/ingest", line 25, in <module>
    mf2 = process_post(post)
  File "/home/donblanco/ditchbook-master/ditchbook/ingest.py", line 55, in process_post
    if NOTE_EXPR.match(post['title']):
KeyError: 'title' ```

not sure what I'm doing wrong here...

**Comment by cleverdevil** [comment]
I don’t think you’re doing anything wrong! Looks like a little bug. I’ll take a crack at fixing it soon!

**Comment by cleverdevil** [comment]
Try updating your installation and trying again. I've made a potential fix.

**Comment by dixonge** [comment]
My wordpress install uses a micropub plugin which provides an endpoint, but not a media endpoint. I'm connect into micro.blog, but using my own domain. If I put micro.blog's media endpoint into conf.py, will that still work? I intend to only bring in some old FB posts. Photo albums I'll be sending to Flickr.

**Comment by cleverdevil** [comment]
Right now, the scripts for publishing assume that both configured endpoints use the same authorization token, so it wouldn’t work for you unless you were able to configure both to share a token.

That said, it would be straightforward for me to add support for this! Let me know if you made it past the “ingest” stage, and if you did, I’ll add support!

**Comment by dshanske** [comment]
Micropub plugin for Wordpress will have one soon

**Comment by dixonge** [comment]
OK, I'll wait for that update then. It also impacts a few other IndieWeb things on WordPress...
