### ISSUE TITLE
bin/publish-post 404 error

### ISSUE THREAD

**Issue by claman** [cleverdevil/ditchbook#5]
Sorry, it's me again! *Finally* getting around to running the import process now that I have some more time, but it's not working. 

I can run `bin/publish-posts` and it'll start cycling text-only posts. Declining to post works as expected, but then I'm getting a 404 error when I try to publish. As far as I can tell, I've changed to `conf.py` as needed.

**Comment by cleverdevil** [comment]
No worries, happy to help if I can. A couple of questions:

1. What CMS are you attempting to publish to? WordPress? Micro.blog? Other?
2. Can you show me the relevant portion of your `conf.py`, with the token redacted? A 404 error indicates that you may be specifying the wrong micropub endpoint.

Thanks.

**Comment by claman** [comment]
1. Micro.blog
2.
```
TOKEN = <redacted>
MP_ENDPOINT = 'https://micro.blog/aclaman'
MP_MEDIA_ENDPOINT = 'https://micro.blog/aclaman/media'
MP_DESTINATION = 'http://aclaman.micro.blog'
```

**Comment by cleverdevil** [comment]
Okay, so your problem here is that you are not specifying the correct micropub endpoint and micropub media endpoint for Micro.blog. What you want is:

```
MP_ENDPOINT = 'https://micro.blog/micropub'
MP_MEDIA_ENDPOINT = 'https://micro.blog/micropub/media'
```

For more detail you can read [Micro.blog's help content on their support for Micropub](https://help.micro.blog/2017/api-posting/).

Let me know if that fixes your issue!

**Comment by claman** [comment]
Thanks! It's working perfectly. Sorry for not being able to read directions

**Comment by cleverdevil** [comment]
Awesome I’m so happy it worked out well for you!
